### ISSUE TITLE
enemy 의 dynamic batching 이 안되는 문제.

### ISSUE THREAD

**Issue by thtjdhdj10** [thtjdhdj10/V_CODE#4]
sprite 의 width / height 를 4의 배수로 바꾸면 해결된다고 함.

**Comment by pjc0247** [comment]
e

**Comment by thtjdhdj10** [comment]
한 게임오브젝트 아래에 복수의 SpriteRenderer 가 있을 때,
그리는 순서를 적절히 지정해주지 않으면,
서로 다른 Sprite 를 동시에 그리게 되어 batching 이 되지 않음.

Order in Layer 를 서로 다르게 설정하면 제대로 batching 됨

**Comment by thtjdhdj10** [comment]
width / height 비율 문제는 텍스쳐 압축을 위한 조건이었음.
2의 거듭제곱을 width/height 로 하는것이 mip-maps 을 쓸 때의 압축조건이고,
4의 배수로 하는것은 DTX5 형식으로 압축하기 위한 조건.

POT 텍스쳐
